language: node_js
sudo: false
node_js:
  - "10"

before_install:
  - npm i -g yarn
  - yarn
script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  target-branch: gh-pages # deploy target branch
  verbose: true
  on:
    branch: master
